version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: agrotech
    command: >
      sh -c "python wait_for_postgres.py &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./agrotech/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - pg

  pg:
    image: postgres
    container_name: pg
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${SQL_DATABASE}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 4s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    container_name: agrotech_adminer
    ports:
      - "8080:8080"

volumes:
  db-data:
