version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: agrotech
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./agrotech/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  pg:
    image: postgres
    container_name: pg
    environment:
      POSTGRES_DB: agrotech
      POSTGRES_USER: username
      POSTGRES_PASSWORD: passwd!
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 4s
      timeout: 5s
      retries: 5

volumes:
  db-data:
