# Generated by Django 4.2.1 on 2023-06-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_id', models.IntegerField(max_length=11)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('investment-areas', 'Инвестиционные направления')], max_length=32)),
                ('description', models.TextField()),
                ('locale', models.CharField(choices=[('kk', 'Kazakh'), ('ru', 'Russian')], default='kk', max_length=4)),
            ],
        ),
    ]
