# Generated by Django 4.2.1 on 2023-06-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='base_id',
            field=models.IntegerField(),
        ),
    ]
