# Generated by Django 4.2.1 on 2023-06-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0002_alter_topic_base_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='base_id',
            field=models.IntegerField(null=True),
        ),
    ]
