# Generated by Django 4.2.1 on 2023-06-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0004_alter_topic_base_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('publication_date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='news_images/')),
                ('locale', models.CharField(choices=[('kk', 'Kazakh'), ('ru', 'Russian')], default='kk', max_length=4)),
            ],
        ),
    ]
