# Generated by Django 4.2.1 on 2023-07-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0006_alter_news_options_alter_news_publication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('department', models.CharField(choices=[('service-soil-science', 'service-soil-science'), ('service-it', 'service-it')], max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='locale',
            field=models.CharField(choices=[('kk', 'Kazakh'), ('ru', 'Russian'), ('en', 'English')], default='kk', max_length=4),
        ),
        migrations.AlterField(
            model_name='topic',
            name='locale',
            field=models.CharField(choices=[('kk', 'Kazakh'), ('ru', 'Russian'), ('en', 'English')], default='kk', max_length=4),
        ),
        migrations.AlterField(
            model_name='topic',
            name='type',
            field=models.CharField(choices=[('investment-areas', 'Инвестиционные направления'), ('projects', 'Проекты')], max_length=32),
        ),
    ]
