# Generated by Django 4.2.1 on 2023-07-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0007_services_alter_news_locale_alter_topic_locale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='locale',
            field=models.CharField(choices=[('kk', 'Kazakh'), ('ru', 'Russian'), ('en', 'English')], default='kk', max_length=4),
        ),
    ]
