# Generated by Django 4.2.1 on 2023-07-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0008_services_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
