# Generated by Django 4.2.1 on 2023-07-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0009_alter_services_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='base_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
