# Generated by Django 4.2.1 on 2023-07-05 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0010_services_base_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_id', models.IntegerField(blank=True, null=True)),
                ('name_kk', models.CharField(max_length=64)),
                ('name_ru', models.CharField(max_length=64)),
                ('name_en', models.CharField(max_length=64)),
                ('description_kk', models.TextField(blank=True, max_length=255, null=True)),
                ('description_ru', models.TextField(blank=True, max_length=255, null=True)),
                ('description_en', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='services',
            name='department',
        ),
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_front.servicecategories'),
        ),
    ]
