# Generated by Django 4.2.1 on 2023-07-05 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0011_servicecategories_remove_services_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategories',
            name='base_id',
        ),
    ]
