# Generated by Django 4.2.1 on 2023-07-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0012_remove_servicecategories_base_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategories',
            name='base_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
