# Generated by Django 4.2.1 on 2023-07-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0013_servicecategories_base_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategories',
            name='base_id',
        ),
    ]
