# Generated by Django 4.2.1 on 2023-07-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0014_remove_servicecategories_base_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.CharField(max_length=64),
        ),
    ]
