# Generated by Django 4.2.1 on 2023-07-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0015_alter_services_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('logo', models.ImageField(upload_to='partners_logo/')),
                ('locale', models.CharField(choices=[('kk', 'Kazakh'), ('ru', 'Russian'), ('en', 'English')], default='kk', max_length=4)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
