# Generated by Django 4.2.1 on 2023-07-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0017_partners_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
