# Generated by Django 4.2.1 on 2023-07-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0018_alter_partners_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partners',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
