# Generated by Django 4.2.1 on 2023-07-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0020_consulting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='consulting_logo/'),
        ),
    ]
