# Generated by Django 4.2.1 on 2023-07-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0021_alter_consulting_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulting',
            name='slug',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
