# Generated by Django 4.2.1 on 2023-08-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0022_consulting_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulting',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategories',
            name='name_en',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servicecategories',
            name='name_kk',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servicecategories',
            name='name_ru',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
