# Generated by Django 4.2.1 on 2023-08-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0023_alter_consulting_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('question', models.TextField(blank=True, max_length=1500, null=True)),
            ],
        ),
    ]
