# Generated by Django 4.2.1 on 2023-09-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0024_trainingrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrequests',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
