# Generated by Django 4.2.1 on 2023-09-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0026_coursecategories_servicecategories_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='base_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
