# Generated by Django 4.2.1 on 2023-10-02 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0027_courses_base_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kk', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kk', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='servicecategories',
            name='contact_phone',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('locale', models.CharField(choices=[('kk', 'Kazakh'), ('ru', 'Russian'), ('en', 'English')], default='kk', max_length=4)),
                ('variety', models.TextField(blank=True, max_length=255, null=True)),
                ('reproduction', models.TextField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(max_length=64)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_front.servicecategories')),
                ('seller', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_front.productseller')),
            ],
        ),
    ]
