# Generated by Django 4.2.1 on 2023-10-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0029_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='reproduction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='variety',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
