# Generated by Django 4.2.1 on 2023-10-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0030_alter_products_reproduction_alter_products_variety'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('event', 'Event'), ('new', 'New')], default='event', max_length=10),
        ),
    ]
