# Generated by Django 4.2.1 on 2024-02-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0031_news_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
