# Generated by Django 4.2.1 on 2024-02-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0032_news_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_kk', models.CharField(max_length=255, null=True)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('description_kk', models.TextField(blank=True, max_length=255, null=True)),
                ('description_ru', models.TextField(blank=True, max_length=255, null=True)),
                ('description_en', models.TextField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
    ]
