# Generated by Django 4.2.1 on 2024-02-19 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0033_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategories',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_front.department'),
        ),
    ]
