# Generated by Django 4.2.1 on 2024-02-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0034_servicecategories_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicecategories',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
