# Generated by Django 4.2.1 on 2024-02-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0036_alter_department_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
