# Generated by Django 4.2.1 on 2024-02-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_front', '0037_services_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='contact_phone',
            field=models.CharField(blank=True, default='', help_text='Whatsapp', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.CharField(max_length=1000),
        ),
    ]
